[project]
site_name = "dataverse-metadata-crawler"
site_description = "A Python CLI tool for bulk extracting and exporting metadata from Dataverse repositories' collections to JSON and CSV formats."
site_author = "Ken Lui"
site_url = "https://scholarsportal.github.io/dataverse-metadata-crawler"
repo_url = "https://github.com/scholarsportal/dataverse-metadata-crawler"
repo_name = "scholarsportal/dataverse-metadata-crawler"
copyright = "&copy; 2026 Ken Lui"
watch = ["src"]
nav = [
  { Home = "index.md" },
  { Usage = "usage.md" },
  # { Reference = "REFERENCE.md" },
]

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

# Palette toggle for light mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

# Palette toggle for dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

[project.markdown_extensions.pymdownx.highlight]
[project.markdown_extensions.pymdownx.superfences]

[project.theme]
features = [
    "search.highlight"
]
[project.plugins.mkdocstrings.handlers.python]
inventories = ["https://docs.python.org/3/objects.inv"]
paths = ["src/dvmeta"]

[project.plugins.mkdocstrings.handlers.python.options]
docstring_style = "google"
inherited_members = true
show_source = true
show_submodules = true
