from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

TITLE_RE = re.compile(r"^#\s+(?P<title>.+)$", re.MULTILINE)
SECTION_RE = re.compile(r"^##\s+`?(?P<name>[^`]+)`?\s*$", re.MULTILINE)
BULLET_RE = re.compile(r"^\*\s+`(?P<item>[^`]+)`:\s*(?P<desc>.*)$")


def run_typer_docs(app_path: str) -> str:
    """Generate Typer documentation as Markdown.

    Args:
        app_path (str): Path to the Typer app module or script.

    Returns:
        str: Raw Markdown generated by Typer.

    """
    result = subprocess.run(
        ["typer", app_path, "utils", "docs"], check=True, capture_output=True, text=True
    )
    return result.stdout


def collapse_whitespace(text: str) -> str:
    """Collapse whitespace into single spaces.

    Args:
        text (str): Input text.

    Returns:
        str: Normalized text.

    """
    return re.sub(r"\s+", " ", text).strip()


def escape_markdown_cell(text: str) -> str:
    """Escape Markdown table cell content.

    Args:
        text (str): Cell text.

    Returns:
        str: Escaped cell text.

    """
    return collapse_whitespace(text).replace("|", "\\|")


def render_table(headers: list[str], rows: list[list[str]]) -> str:
    """Render a Markdown table.

    Args:
        headers (list[str]): Table headers.
        rows (list[list[str]]): Table rows.

    Returns:
        str: Markdown table.

    """
    escaped_headers = [escape_markdown_cell(header) for header in headers]
    escaped_rows = [[escape_markdown_cell(cell) for cell in row] for row in rows]

    header_line = "| " + " | ".join(escaped_headers) + " |"
    separator_line = "| " + " | ".join(["---"] * len(headers)) + " |"
    body_lines = ["| " + " | ".join(row) + " |" for row in escaped_rows]

    return "\n".join([header_line, separator_line, *body_lines])


def parse_bullets(block: str) -> list[tuple[str, str]]:
    """Parse Typer bullet lists into item-description pairs.

    Args:
        block (str): Markdown block containing bullet items.

    Returns:
        list[tuple[str, str]]: Parsed bullet items.

    """
    rows: list[tuple[str, str]] = []
    current_item: str | None = None
    current_desc: list[str] = []

    for raw_line in block.splitlines():
        line = raw_line.strip()
        if not line:
            continue

        match = BULLET_RE.match(line)
        if match:
            if current_item is not None:
                rows.append((current_item, collapse_whitespace(" ".join(current_desc))))
            current_item = match.group("item").strip()
            current_desc = [match.group("desc").strip()]
            continue

        if current_item is not None:
            current_desc.append(line)

    if current_item is not None:
        rows.append((current_item, collapse_whitespace(" ".join(current_desc))))

    return rows


def split_option_item(item: str) -> tuple[str, str]:
    """Split an option label into display name and value/type hint.

    Args:
        item (str): Raw option label from Typer.

    Returns:
        tuple[str, str]: Option label and value/type hint.

    """
    if "<" in item and item.endswith(">"):
        label, value = item.rsplit("<", 1)
        return label.strip(), f"<{value.strip()}"
    return item.strip(), ""


def extract_title(text: str) -> str:
    """Extract the top-level title from Markdown.

    Args:
        text (str): Markdown text.

    Returns:
        str: Title string, or an empty string if missing.

    """
    match = TITLE_RE.search(text)
    return match.group("title").strip() if match else ""


def first_section_start(text: str) -> int:
    """Find the start position of the first second-level section.

    Args:
        text (str): Markdown text.

    Returns:
        int: Character index of the first second-level heading, or -1 if none exists.

    """
    match = SECTION_RE.search(text)
    return match.start() if match else -1


def split_at_earliest_marker(text: str, markers: list[str]) -> tuple[str, str]:
    """Split text at the earliest matching marker.

    Args:
        text (str): Input text.
        markers (list[str]): Markers to search for.

    Returns:
        tuple[str, str]: Text before the marker and the remaining text starting at the marker.

    """
    positions = [(text.find(marker), marker) for marker in markers if marker in text]
    if not positions:
        return text.strip(), ""

    pos, _ = min(positions, key=lambda item: item[0])
    return text[:pos].strip(), text[pos:].strip()


def extract_main_blocks(text: str) -> tuple[str, str, str, str]:
    """Extract intro, usage, options, and commands from the main CLI block.

    Args:
        text (str): Main CLI block.

    Returns:
        tuple[str, str, str, str]: Intro, usage, options, and commands blocks.

    """
    intro = text.strip()
    usage = ""
    options = ""
    commands = ""

    if "**Usage**:" not in text:
        return intro, usage, options, commands

    intro, _, after_usage_marker = text.partition("**Usage**:")
    usage, remainder = split_at_earliest_marker(
        after_usage_marker, ["**Options**:", "**Commands**:"]
    )

    if remainder.startswith("**Options**:"):
        _, _, after_options_marker = remainder.partition("**Options**:")
        options, remainder = split_at_earliest_marker(after_options_marker, ["**Commands**:"])
    if remainder.startswith("**Commands**:"):
        _, _, after_commands_marker = remainder.partition("**Commands**:")
        commands = after_commands_marker.strip()

    return intro.strip(), usage.strip(), options.strip(), commands.strip()


def extract_command_block(text: str) -> tuple[str, str, str]:
    """Extract description, usage, and options from a command section.

    Args:
        text (str): Command section body.

    Returns:
        tuple[str, str, str]: Description, usage, and options blocks.

    """
    description = text.strip()
    usage = ""
    options = ""

    if "**Usage**:" not in text:
        return description, usage, options

    description, _, after_usage_marker = text.partition("**Usage**:")
    usage, remainder = split_at_earliest_marker(after_usage_marker, ["**Options**:"])

    if remainder.startswith("**Options**:"):
        _, _, after_options_marker = remainder.partition("**Options**:")
        options = after_options_marker.strip()

    return description.strip(), usage.strip(), options.strip()


def rewrite_markdown(raw_markdown: str) -> str:
    """Rewrite Typer Markdown into a table-oriented document.

    Args:
        raw_markdown (str): Raw Typer-generated Markdown.

    Returns:
        str: Rewritten Markdown.

    """
    lines = raw_markdown.splitlines()
    first_section_index = first_section_start(raw_markdown)

    main_block = (
        raw_markdown[:first_section_index].strip()
        if first_section_index != -1
        else raw_markdown.strip()
    )
    command_sections = (
        raw_markdown[first_section_index:].strip() if first_section_index != -1 else ""
    )

    title = extract_title(main_block)
    after_title = main_block
    if title:
        title_line = f"# {title}"
        _, _, after_title = main_block.partition(title_line)
        after_title = after_title.strip()

    intro, usage, options, commands = extract_main_blocks(after_title)

    output: list[str] = []

    if title:
        output.append(f"# {title}")
        output.append("")

    if intro:
        output.append(intro)
        output.append("")

    if usage:
        output.append("## Usage")
        output.append("")
        output.append(usage)
        output.append("")

    global_option_rows = []
    for item, desc in parse_bullets(options):
        option_label, value_hint = split_option_item(item)
        global_option_rows.append([option_label, value_hint, desc])

    if global_option_rows:
        output.append("## Global Options")
        output.append("")
        output.append(render_table(["Option", "Value / Type", "Description"], global_option_rows))
        output.append("")

    command_rows = []
    for item, desc in parse_bullets(commands):
        command_rows.append([item, desc])

    if command_rows:
        output.append("## Commands")
        output.append("")
        output.append(render_table(["Command", "Description"], command_rows))
        output.append("")

    if command_sections:
        section_matches = list(SECTION_RE.finditer(command_sections))
        for index, match in enumerate(section_matches):
            section_name = match.group("name").strip()
            section_start = match.end()
            section_end = (
                section_matches[index + 1].start()
                if index + 1 < len(section_matches)
                else len(command_sections)
            )
            section_body = command_sections[section_start:section_end].strip()

            description, usage_block, options_block = extract_command_block(section_body)

            output.append(f"## `{section_name}`")
            output.append("")

            if description:
                output.append(description)
                output.append("")

            if usage_block:
                output.append(usage_block)
                output.append("")

            section_option_rows = []
            for item, desc in parse_bullets(options_block):
                option_label, value_hint = split_option_item(item)
                section_option_rows.append([option_label, value_hint, desc])

            if section_option_rows:
                output.append(
                    render_table(["Option", "Value / Type", "Description"], section_option_rows)
                )
                output.append("")

    return "\n".join(output).rstrip() + "\n"


def main() -> int:
    """Run the CLI documentation generator.

    Args:
        None

    Returns:
        int: Process exit code.

    """
    parser = argparse.ArgumentParser(description="Generate and rewrite Typer CLI docs.")
    parser.add_argument("app", help="Path to the Typer app script or module.")
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=Path("USAGE.md"),
        help="Write the rewritten Markdown to this file.",
    )
    args = parser.parse_args()

    try:
        raw_markdown = run_typer_docs(args.app)
    except subprocess.CalledProcessError as exc:
        sys.stderr.write(exc.stderr or str(exc))
        sys.stderr.write("\n")
        return exc.returncode or 1

    rewritten = rewrite_markdown(raw_markdown)
    args.output.write_text(rewritten, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
